### ISSUE TITLE
[Bug] Potential Assembly PCB Parts Mismatch

### ISSUE THREAD

**Issue by YuHoChau** [binghao-huang/3D-ViTac_Tactile_Hardware#1]
Hi Binghao, thank you for sharing your latest awesome work. I was trying to reproduce your project and noticed a potential mismatch with some PCB components, based on the files shared in the guide doc on 11/14. Specifically:

1. For `Gerber_Connector`, there’s no need to solder the `16 Pin Header`, there are no pre-drilled holes, and your tutorial video shows using tape to directly attach the conductive thread.

2. For `Gerber_Reading_Board`, two `16 Pin Headers` are required, which need to be manually soldered if not pre-assembled by the company.

It would be very helpful if these details were included in your hardware guide documentation.

Meanwhile, since I have not yet tried your developed sensor, I was wondering if directly using your 16-pin connector and board would be compatible with a smaller-sized sensor array? For example, for one connector, using only 10 channels (which reduces the pad size to ~3cm) would this still work without designing a new 10-channel board? Thanks!

**Comment by binghao-huang** [comment]
Here’s a revised version of your text with improved clarity and grammar:

Thank you! Yes, these two points are correct. I will include them in the guide.

The system is definitely compatible with smaller-sized sensor arrays. I have tested it with multiple different channels without even modifying the Arduino code. If you adjust the Arduino code to reduce the number of channels, you can achieve a higher reading frequency.

**Comment by YuHoChau** [comment]
Great! Thank you for your prompt response!
